version: "3.7"

services:
  db:
    image: mysql:5.7
    container_name: my-savings-db-dev
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: my_savings_db_dev
      MYSQL_USER: my_savings_db
      MYSQL_PASSWORD: my_savings_db
      MYSQL_ROOT_PASSWORD: my_savings_db
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      - my_savings_network

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: https://ghcr.io/faizaleticia/my-savings/my-savings-app-dev
    container_name: my-savings-app-dev
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - my_savings_network

networks:
  my_savings_network:
    driver: bridge
volumes:
  mysqldata:
    driver: local
