name: Server Deploy Development

on:
  push:
    branches:
      - main
      - features/**
      - dependabot/**
  pull_request:
    branches:
      - main

jobs:
  server-deploy-development:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Enter server folder
        run: cd server
      - name: Build server containers
        run: docker-compose -f "docker-compose.yml" build --no-cache
