version: "3.7"

services:
  app:
    container_name: my-savings-web-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  prod:
    container_name: my-savings-web-prod
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
