version: "3.7"

services:
  app:
    container_name: my-savings-web-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    image: ghcr.io/faizaleticia/my-savings/my-savings-web-dev
